name: PHP Code Style Fixer

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - master
#       - develop
#       - "release/**"
#       - "hotfix/**"
#   pull_request:
#     branches:
#       - main

jobs:
  phpcs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --dev

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcbf --standard=phpcs.xml --extensions=php --ignore=vendor . || true

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Fix code style" --no-verify
          git push
