name: PHP Static Analysis

on: [push, pull_request]
# on:
#   push:
#     branches:
#       - master
#       - develop
#       - "release/**"
#       - "hotfix/**"
#   pull_request:
#     branches:
#       - main

jobs:
  phpstan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --dev

      - name: Run PHPStan
        run: |
          vendor/bin/phpstan analyse --memory-limit=512M --no-progress --error-format=json > phpstan.json || true

      - name: Upload PHPStan Report
        uses: actions/upload-artifact@v2
        with:
          name: phpstan-report
          path: phpstan.json

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Report PHPStan" --no-verify
          git push
